catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
packages:
  - examples/**
  - packages/**
  - apps/**
overrides:
  array-flatten: npm:@nolyfill/array-flatten@^1.0.44
  axios: npm:feaxios@^0.0.23
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  isarray: npm:@nolyfill/isarray@^1.0.44
  safe-buffer: npm:@nolyfill/safe-buffer@^1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@^1.0.44
  side-channel: npm:@nolyfill/side-channel@^1.0.44
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@^1.0.44

catalog:
  '@antfu/eslint-config': ^7.4.3
  '@antfu/ni': ^28.2.0
  '@antfu/nip': ^0.1.1
  '@arethetypeswrong/cli': ^0.18.2
  '@catppuccin/palette': ^1.7.1
  '@iconify-json/carbon': ^1.2.18
  '@iconify-json/line-md': ^1.2.14
  '@iconify-json/simple-icons': ^1.2.70
  '@iconify-json/solar': ^1.2.5
  '@iconify-json/svg-spinners': ^1.2.4
  '@pnpm/find-workspace-dir': ^1000.1.4
  '@types/node': ^25.2.3
  '@unocss/eslint-config': ^66.6.0
  '@unocss/eslint-plugin': ^66.6.0
  '@unocss/preset-mini': ^66.6.0
  '@unocss/reset': ^66.6.0
  '@vitejs/plugin-vue': ^6.0.4
  '@vueuse/core': ^14.2.1
  '@vueuse/motion': ^3.0.3
  '@webgpu/types': ^0.1.69
  bumpp: ^10.4.1
  changelogithub: ^14.0.0
  es-toolkit: ^1.44.0
  eslint: ^9.39.2
  eslint-plugin-import-x: ^4.16.1
  gpuu: ^1.0.6
  rollup: ^4.57.1
  splitpanes: ^4.0.4
  taze: ^19.9.2
  tsx: ^4.21.0
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unocss: 66.6.0
  unocss-preset-scrollbar: ^3.2.0
  unplugin-vue-router: ^0.19.2
  vite: ^7.3.1
  vite-plugin-inspect: ^11.3.3
  vitest: ^4.0.18
  vue: ^3.5.28
  vue-router: ^5.0.2
  vue-tsc: ^3.2.4
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
